// Code generaTed by fileb0x at "2026-06-15 23:37:00.211418281 +0200 CEST m=+0.153056054" from config file "b0x.yaml" DO NOT EDIT.
// modified(2026-06-15 23:13:27.636338003 +0200 CEST)
// original path: swagger-ui/dist/oauth2-redirect.html

package swaggerFiles

import (
	"os"
)

// FileOauth2RedirectHTML is "/oauth2-redirect.html"
var FileOauth2RedirectHTML = []byte("\x3c\x21\x64\x6f\x63\x74\x79\x70\x65\x20\x68\x74\x6d\x6c\x3e\x0a\x3c\x68\x74\x6d\x6c\x20\x6c\x61\x6e\x67\x3d\x22\x65\x6e\x2d\x55\x53\x22\x3e\x0a\x3c\x62\x6f\x64\x79\x3e\x0a\x3c\x73\x63\x72\x69\x70\x74\x20\x73\x72\x63\x3d\x22\x6f\x61\x75\x74\x68\x32\x2d\x72\x65\x64\x69\x72\x65\x63\x74\x2e\x6a\x73\x22\x3e\x3c\x2f\x73\x63\x72\x69\x70\x74\x3e\x0a\x3c\x2f\x62\x6f\x64\x79\x3e\x0a\x3c\x2f\x68\x74\x6d\x6c\x3e\x0a")

func init() {

	f, err := FS.OpenFile(CTX, "/oauth2-redirect.html", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileOauth2RedirectHTML)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
